project:
  type: website
  output-dir: docs

website:
  title: "Nicolás Sacco"
  description: "Personal website of Nicolás Sacco"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

